- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: Deploying Application pods...
      shell: | 
          if [ `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep trainings | wc -l` -gt 0 ]; then  
            echo "deleteing previous application deployment"
            kubectl delete deployment `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep trainings`
         else 
            echo "Deploying training_schedule Application"
            kubectl create deployment trainings --image=elchen8923/training-schedule:{{ build }}
         fi

    - name: Deploying service
      shell: |
         if [ `kubectl get svc | grep trainings  | awk '{print $1}' | wc -l` -gt 0 ]; then
            echo "app service found, delete the service"
            kubectl delete svc `kubectl get svc | grep trainings | awk '{print $1}'`
         else
            echo "Creating App Services"
            kubectl expose deployment trainings --name trainings --type NodePort --port 8080 --target-port 30001
         fi

    - name: Increase replicas 
      shell: kubectl scale deploy trainings --replicas=2