- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: Deploying Application pods...
      shell: | 
         if [ `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep training_schedule | wc -l` -gt 0 ]; then  
            echo "deleteing previous application deployment"
            kubectl delete deployment `kubectl get deployment | grep -v NAME | awk '{print $1}' | grep training_schedule`
         fi
         if [ `kubectl get svc | grep training-schedule  | awk '{print $1}' | wc -l` -gt 0 ]; then
            echo "app service found, delete the service"
            kubectl delete svc `kubectl get svc | grep training-schedule | awk '{print $1}'`
         fi
         echo "Deploying training-schedule Application"
         kubectl create -f train-schedule-kube.yml